# Define some usefull exceptions 

class NameConflict(ValueError):
    '''Represent a name conflict which cannot be resolved automatically.
    '''
    pass

class IdentifierConflict(ValueError):
    '''Represent an identifier conflict.

    This type of exception can only appear if an identifier is present is an
    imported/harvested dataset (by default identifiers are autogenerated as UUIDs,
    and will never conflict).
    '''
    pass

class InvalidParameter(ValueError):
    '''Represent an invalid parameter passed to an action.
    '''
    def __init__(self, msg, parameter_name=None):
        super(InvalidParameter, self).__init__(msg)
        self.parameter_name = parameter_name
   

# Import action modules

from ckanext.publicamundi.lib.actions import package
from ckanext.publicamundi.lib.actions import autocomplete

