# -*- coding: utf-8 -*-

languages = [
            "Bulgarian",
            "Czech",
            "Danish",
            "Dutch",
            "English",
            "Estonian",
            "Finnish",
            "French",
            "German",
            "Greek",
            "Hungarian",
            "Irish",
            "Italian",
            "Latvian",
            "Lithuanian",
            "Maltese",
            "Polish",
            "Portuguese",
            "Romanian",
            "Slovak",
            "Slovenian",
            "Spanish",
            "Swedish"]

topic_category = [
            "Farming",
            "Biota",
            "Boundaries",
            "ClimatologyMeteorologyAtmosphere",
            "Economy",
            "Elevation",
            "Environment",
            "GeoscientificInformation",
            "Health",
            "ImageryBaseMapsEarthCover",
            "IntelligenceMilitary",
            "InlandWaters",
            "Location",
            "Oceans",
            "PlanningCadastre",
            "Society",
            "Structure",
            "Transportation",
            "UtilitiesCommunication"]




countries = [
        "Albania",
            "Andorra",
            "Austria",
            "Azores",
            "Belarus",
            "Belgium",
            "Bosnia and Herzegovina",
            "Bulgaria",
            "Canaries",
            "Croatia",
            "Cyprus",
            "Czech Republic",
            "Denmark",
            "Estonia",
            "EU-12",
            "EU-15",
            "EU-25",
            "EU-27",
            "Finland",
            "Former Yugoslav Republic of Macedonia",
            "France",
            "France Continental",
            "French Guiana",
            "Germany",
            "Gibraltar",
            "Greece",
            "Guadeloupe",
            "Holy See Vatican City State",
            "Hungary",
            "Ireland",
            "Isle of Man",
            "italy",
            "Latvia",
            "Liechtenstein",
            "Lithuania",
            "Luxembourg",
            "Madeira",
            "Malta",
            "Martinique",
            "Moldova",
            "Morocco",
            "Netherlands",
            "Norway",
            "Poland",
            "Portugal",
            "Portugal Continental",
            "Romania",
            "Russian Federation",
            "Reunion",
            "Saint-Berthelemy",
            "Saint-Martin",
            "San Marino",
            "Slovakia",
            "Slovenia",
            "Spain",
            "Spain Continental",
            "Sweden",
            "Switzerland",
            "Turkey",
            "Ukraine",
            "United Kingdom",
            "World",]


date_type = [
            "creation",
            "publication",
            "revision"]

degree = [
	"Not evaluated",
	"Not conformant",
	"Conformant"]

party_roles= [
            "ResourceProvider",
            "Custodian",
            "Owner",
            "User",
            "Distributor",
            "Originator",
            "PointOfContact",
            "PrincipalInvestigator",
            "Processor",
            "Publisher",
            "Author"]




topic_category_gr = [
            "Βιόκοσμος",
            "Γεωγραφική θέση",
            "Γεωεπιστημονικές πληροφορίες",
            "Γεωργία",
            "Επιχειρήσεις κοινής ωφελείας/Επικοινωνία",
            "Εσωτερικά ύδατα",
            "Θάλασσες",
            "Κατασκευές",
            "Κλιματολογία/Μετεωρολογία/Ατμόσφαιρα",
            "Κοινωνία",
            "Μεταφορές",
            "Οικονομία",
            "Ορθοεικόνες/Βασικοί χάρτες/Κάλυψη γης",
            "Περιβάλλον",
            "Στρατιωτικές πληροφορίες",
            "Υγεία",
            "Υψομετρία",
            "Χωροταξία/Κτηματολόγιο",
            "Όρια"]


inspire_data_themes_gr = [
            "Έδαφος",
            "Ανθρώπινη υγεία και ασφάλεια",
            "Ατμοσφαιρικές συνθήκες",
            "Βιογεωγραφικές περιοχές",
            "Γεωλογία",
            "Γεωργικές εγκαταστάσεις και εγκαταστάσεις υδατοκαλλιέργειας",
            "Γεωτεμάχια κτηματολογίου",
            "Δίκτυα μεταφορών",
            "Διευθύνσεις",
            "Διοικητικές ενότητες",
            "Εγκαταστάσεις παραγωγής και βιομηχανικές εγκαταστάσεις",
            "Εγκαταστάσεις παρακολούθησης του περιβάλλοντος",
            "Ενδιαιτήματα και βιότοποι",
            "Ενεργειακοί πόροι",
            "Επιχειρήσεις κοινής ωφελείας και κρατικές υπηρεσίες",
            "Ζώνες διαχείρισης/περιορισμού/ρύθμισης εκτάσεων και μονάδες αναφοράς",
            "Ζώνες φυσικών κινδύνων",
            "Θαλάσσιες περιοχές",
            "Κάλυψη γης",
            "Κατανομή ειδών",
            "Κατανομή πληθυσμού - δημογραφία",
            "Κτίρια",
            "Μετεωρολογικά γεωγραφικά χαρακτηριστικά",
            "Ορθοφωτογραφία",
            "Ορυκτοί πόροι",
            "Προστατευόμενες τοποθεσίες",
            "Στατιστικές μονάδες",
            "Συστήματα γεωγραφικού καννάβου",
            "Συστήματα συντεταγμένων",
            "Τοπωνύμια",
            "Υδρογραφία",
            "Υψομετρία",
            "Χρήσεις γης",
            "Ωκεανογραφικά γεωγραφικά χαρακτηριστικά"]


date_type_gr = [
      "Ημερομηνία δημιουργίας",
      "Ημερομηνία δημοσίευσης",
      "Ημερομηνία τελευταίας αναθεώρησης"]


responsible_party_role_gr = [
            "Αρμόδιος για επικοινωνία",
            "Δημιουργός",
            "Διανομέας",
            "Εκδότης",
            "Επεξεργαστής",
            "Κάτοχος",
            "Πάροχος πόρου",
            "Πρωτεύων διερευνητής",
            "Συντάκτης",
            "Υπόλογος",
            "Χρήστης"]


